image: registry.ddbuild.io/images/mirror/golang:1.23.4

stages:
  - build
  - test

build:
  stage: build
  tags:
    - "arch:amd64"
  script:
    - echo "Building the project..."
    - echo "Done building the project."

tests:
  stage: test
  image: registry.ddbuild.io/images/mirror/golang:1.23.4
  tags:
    - "arch:amd64"
  before_script:
    - curl -L https://github.com/opentofu/opentofu/releases/download/v1.9.1/tofu_1.9.1_linux_amd64.tar.gz -o tofu.tar.gz
    - tar -xzf tofu.tar.gz
    - mv tofu /usr/local/bin/tofu
    - chmod +x /usr/local/bin/tofu
    - tofu version
    - echo "Assuming ddbuild-agent-ci role"
    - roleoutput=$(aws sts assume-role --role-arn arn:aws:iam::669783387624:role/ddbuild-terraform-aws-ecs-datadog --external-id ddbuild-terraform-aws-ecs-datadog-ci --role-session-name RoleSession)
    - export AWS_ACCESS_KEY_ID="$(echo "$roleoutput" | jq -r '.Credentials.AccessKeyId')"
    - export AWS_SECRET_ACCESS_KEY="$(echo "$roleoutput" | jq -r '.Credentials.SecretAccessKey')"
    - export AWS_SESSION_TOKEN="$(echo "$roleoutput" | jq -r '.Credentials.SessionToken')"
  script:
    - make test
