name: Check Terraform Docs

permissions:
  contents: read

on:
  pull_request:
    paths:
      - "modules/ecs_fargate/**"
  workflow_dispatch:

jobs:
  terraform-docs:
    name: Check terraform-docs for ecs_fargate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: "1.23"

      - name: Install terraform-docs
        run: |
          VERSION="v0.19.0"
          OS=$(uname -s | tr '[:upper:]' '[:lower:]')
          ARCH=$(uname -m)
          if [ "$ARCH" = "x86_64" ]; then ARCH="amd64"; fi
          URL="https://github.com/terraform-docs/terraform-docs/releases/download/${VERSION}/terraform-docs-${VERSION}-${OS}-${ARCH}.tar.gz"
          echo "Downloading terraform-docs from $URL"
          curl -sSLo terraform-docs.tar.gz "$URL"
          tar -xzf terraform-docs.tar.gz terraform-docs
          sudo mv terraform-docs /usr/local/bin/

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2 v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: modules/ecs_fargate
        run: terraform init -backend=false

      - name: Generate docs and check for drift
        working-directory: modules/ecs_fargate
        run: |
          cp README.md /tmp/README.md.bak
          terraform-docs . --config ../../.terraform-docs.yml
          if ! diff README.md /tmp/README.md.bak > /dev/null; then
            echo "::error::Documentation is out of date. Please run 'make docs' in modules/ecs_fargate and commit the changes."
            echo "Diff:"
            diff README.md /tmp/README.md.bak || true
            exit 1
          fi
